version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: my3d-bambuddy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/mikefox303/bambuddy:1.2.5.5-x2d.73@sha256:9abf0d5bfb612dd1f473a7632f2b7aa404ef06db759e979b388bd7466cc84fb0
    restart: on-failure
    init: true
    environment:
      TZ: Europe/Kyiv
      PUID: "1000"
      PGID: "1000"
      PORT: "8000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
