version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: my3d-bambuddy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/mikefox303/bambuddy:1.2.5.4-x2d.29@sha256:0e444929b4bcd3c4e1fe4e9423c8d2a1167f50eab9aa1c33319333adf2a7d6c8
    restart: on-failure
    init: true
    environment:
      TZ: Europe/Kyiv
      PUID: "1000"
      PGID: "1000"
      PORT: "8000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
