version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: my3d-bambuddy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/maziggy/bambuddy:1.2.5.5@sha256:dc627d618cc3d3252ae4ab33af74c4679c66a9a06e0e3bbb7aefa32d1a4d4a07
    restart: on-failure
    init: true
    environment:
      TZ: Europe/Kyiv
      PUID: "1000"
      PGID: "1000"
      PORT: "8000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
